server:
  port: 8085

spring:
  application:
    name: notification-service

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: 'true'

rabbitmq:
  exchanges:
    internal: notification.exchange
  queues:
    send-email: send.email.queue
  routing-keys:
    send-email: send.email.routing-key