server:
  port: 8086

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: file-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true