server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory
    username: ahmetcan7
    password: ahmetcan123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  application:
    name: inventory-service

rabbitmq:
  exchanges:
    internal: inventory.exchange
  queues:
    create-inventory: create.inventory.queue
    delete-inventory: delete.inventory.queue
    update-inventory: update.inventory.queue
  routing-keys:
    create-inventory: create.inventory.routing-key
    delete-inventory: delete.inventory.routing-key
    update-inventory: update.inventory.routing-key

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true