server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory
    username: ahmetcan7
    password: ahmetcan123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  application:
    name: inventory-service

rabbitmq:
  exchanges:
    internal: inventory.exchange
  queues:
    inventory: notification.queue
  routing-keys:
    internal-inventory: internal.inventory.routing-key

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}